# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-CaptchasDotNet
version:      0.06
version_from: CaptchasDotNet.pm
installdirs:  site
requires:
    Cwd:                           0
    Digest::MD5:                   0
    File::Path:                    0
    File::Spec:                    0
    IO::Dir:                       0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
